# Derived short-run config for 100-epoch experiment with log-sigma enabled
# 100-epoch short config (self-contained copy of Interaction_tmp without relative import)

# model
OB_RADIUS = 10000
OB_HORIZON = 8
PRED_HORIZON = 25
INCLUSIVE_GROUPS = ["car"]
RNN_HIDDEN_DIM = 512

# training
LEARNING_RATE = 1e-4
BATCH_SIZE = 128
EPOCHS = 100
EPOCH_BATCHES = 100
TEST_SINCE = 50

# testing
PRED_SAMPLES = 20
FPC_SEARCH_RANGE = range(40,50)

WORLD_SCALE = 1

RISK_ENABLE = True
RISK_WEIGHT = 0.2
RISK_GLOBAL_SCALE = 1.0
RISK_COMPONENT_WEIGHTS = {
	"risk_min_dist": 0.35,
	"risk_ttc": 0.15,
	"risk_pet": 0.25,
	"risk_overlap": 0.25,
}
RISK_LEARN_COMPONENT_WEIGHTS = True
RISK_LEARN_COMPONENT_NORM = 'softmax'
RISK_COMPW_ENTROPY_LAMBDA = 0.01
RISK_MIN_DIST_BETA = 3.0
RISK_TTC_TAU = 1.5
RISK_PET_DIST_TH = 2.0
RISK_PET_ALPHA = 8.0
RISK_PET_BETA = 0.7
RISK_PET_GAMMA = 2.0
RISK_PET_CONTINUOUS = True
RISK_PET_TIME_TEMP = 4.0
RISK_OV_R_SELF = 0.5
RISK_OV_R_NEIGH = 0.5
RISK_OV_MARGIN = 0.3
RISK_OV_K = 15.0
RISK_OV_TIME_TEMP = 4.0
RISK_OV_NEIGH_TEMP = 3.0
RISK_OV_USE_OBB = True
RISK_OV_SELF_LENGTH = 4.5
RISK_OV_SELF_WIDTH = 1.8
RISK_OV_NEIGH_LENGTH = 4.5
RISK_OV_NEIGH_WIDTH = 1.8
RISK_OV_MIN_SPEED = 1e-3
RISK_OV_AXIS_BETA = 12.0
RISK_OV_DEBUG = True
RISK_ENABLE_PET = True
RISK_ENABLE_OVERLAP = True
RISK_MULTI_SAMPLES = 1
RISK_MULTI_TEMP = 4.0
RISK_USE_LOG_SIGMA = True
RISK_LOG_SIGMA_PENALTY_W = 0.01

LOSS_W_REC = 1.0
LOSS_W_WMSE = 0.2
LOSS_W_KL = 0.1
LOSS_W_ADV = 0.01
LOSS_W_KIN = 0.05
LOSS_COMBINE_REC_WMSE = False
LOSS_REC_WMSE_ALPHA = 0.3
